name: GitHub multiple docker images building Demo
on: [push]
jobs:
  Explore-double-docker-images-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: zuhaibasgher/testingRepo@main
    - name: build first docker image
      run: 
        cd docker/first/
        docker build ./docker/first/ -t first_image
    - name: build second docker image
      run: 
         cd docker/second/
        docker build ./docker/second/ -t second_image
