name: GitHub multiple docker images building Dem
on: [push]
jobs:
	run-on: ubuntu-latest
steps:
	uses: zuhaibasgher/testingRepo@main
	-name: first docker image
		run: docker build -f /zuhaibasgher/testingRepo/docker/first/Dockerfile
	-name: second docker image
		run: docker build -f /zuhaibasgher/testingRepo/docker/second/Dockerfile
		run: echo "second docker is running"
			
			
