name: GitHub multiple docker images building Demo
on: [push]
jobs:
run-on: ubuntu-latest
steps:
	-name: building docker images
		run: docker-compose build
	-name: run first docker image
		run: docker-compose run /docker/first
		run: echo "first docker is running"
	-name: run second docker image
		run: docker-compose run /docker/second
		run: echo "second docker is running"
			
			
