name: GitHub multiple docker images building Demo
on: [push]
jobs:
  Explore-double-docker-images-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: build first docker image
      run:  docker build ./docker/first/
    - name: build second docker image
      run:  docker build ./docker/second/
