name: GitHub multiple docker images building Demo
on: [push]
jobs:
  Explore-double-docker-images-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: zuhaibasgher/testingRepo@main
    - name: build first docker image
      run: docker build --file ./docker/first/Dockerfile --tag firstImage
    - name: buidl second docker image
      run: docker build --file ./docker/second/Dockerfile --tag secondImage
