name: GitHub multiple jobs running
on: [push]
jobs:
  First:
   name: First
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - name: build first docker image
       run:  docker build ./docker/first/ --tag first_image
     - name: List images
       run: docker images  
  Second:
   needs: First
   name: Second
   runs-on: ubuntu-latest
   steps:
      - name: testing second job
        run: echo "Just a test for 2nd job"
